# Generated by Django 2.0.2 on 2018-06-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180411_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('article_id', models.IntegerField()),
            ],
        ),
    ]
