# Generated by Django 2.0.2 on 2018-06-29 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180629_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='creat',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 29, 12, 27, 6, 137006, tzinfo=utc)),
        ),
    ]
