# Generated by Django 2.0.2 on 2018-05-23 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='courses_join', to=settings.AUTH_USER_MODEL),
        ),
    ]
